fdrw.conf V1.0

11 /data/app/com.amazon.claydoodle.apk
12 /data/app/com.amazon.claydoodle-1.apk
13 /data/app/com.amazon.claydoodle-2.apk
14 /data/app/com.amazon.monkeybuddy.apk
15 /data/app/com.amazon.monkeybuddy-1.apk
16 /data/app/com.amazon.monkeybuddy-2.apk
17 /data/app/com.amazon.planetpuzzles.apk
18 /data/app/com.amazon.planetpuzzles-1.apk
19 /data/app/com.amazon.planetpuzzles-2.apk
